# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 11:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artical',
            name='category',
        ),
        migrations.AddField(
            model_name='category',
            name='artical',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Blog.Artical', verbose_name='分类'),
        ),
    ]
