# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 08:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_auto_20170127_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='artical',
        ),
        migrations.AddField(
            model_name='artical',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Blog.Category', verbose_name='分类'),
        ),
    ]
