# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 09:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_auto_20170128_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=10, verbose_name='评论者名字')),
                ('body', models.TextField(verbose_name='评论内容')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('artical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.Artical')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='标签')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('last_modified_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='artical',
            name='tags',
            field=models.ManyToManyField(null=True, to='Blog.Tag', verbose_name='标签'),
        ),
    ]
