# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-30 16:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_auto_20170130_2231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artical',
            name='abstract',
        ),
        migrations.RemoveField(
            model_name='artical',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
